# Generated by Django 2.2 on 2019-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_basket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('cmp', 'completed'), ('prc', 'processing')], max_length=20, null=True),
        ),
    ]
