# Generated by Django 2.2 on 2019-04-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190422_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('cmp', 'completed'), ('prc', 'processing')], default=('prc', 'processing'), max_length=20),
        ),
    ]
