# Generated by Django 2.2 on 2019-04-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190422_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('cmp', 'completed'), ('prc', 'processing')], default=2, max_length=20),
        ),
    ]
