# Generated by Django 2.2 on 2019-04-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190422_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('cmp', 'completed'), ('prc', 'processing')], default='prc', max_length=20),
        ),
    ]
